// auth
export const LOGIN_WITH_FIREBASE = 'LOGIN_WITH_FIREBASE'
export const LOGOUT_WITH_FIREBASE = 'LOGOUT_WITH_FIREBASE'
export const REGISTER_IN_FIREBASE = 'REGISTER_IN FIREBASE'
// user
export const FETCH_INFO_USER = 'FETCH_INFO_USER'
// fixer
export const FETCH_CURRENCY = 'FETCH_CURRENCY'
